name: Deploy to EC2

on:
  push:
    branches: [ main ]
  repository_dispatch:
    types: [ frontend-updated, ai-service-updated ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/ubuntu/meet-u-career
            git pull origin main
            docker-compose down
            docker-compose up -d --build
          EOF
