name: Backend Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: SSH Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Copy Files to EC2
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./ ubuntu@${{ secrets.EC2_HOST }}:~/meet-u-backend

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/meet-u-backend
            echo "Stopping old containers..."
            docker-compose down
            echo "Starting new containers..."
            docker-compose up -d --build
          EOF

